steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['package']
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/$PROJECT_ID/helper:$COMMIT_SHA", "-t", "gcr.io/$PROJECT_ID/helper:latest", "-f", "Dockerfile", "."]
images:
  - 'gcr.io/$PROJECT_ID/helper:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/helper:latest'
