apiVersion: v1
kind: ConfigMap
metadata:
  name: postgis-config
  namespace: default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgis-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgis
spec:
  template:
    metadata:
      labels:
        app: postgis
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgis-pv-claim
      containers:
        - image: mdillon/postgis
          name: postgis
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgis
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgis
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgis
